// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sql_model

import (
	"time"
)

const TableNameCouponVerify = "coupon_verify"

// CouponVerify mapped from table <coupon_verify>
type CouponVerify struct {
	ID             int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CouponID       int64     `gorm:"column:coupon_id;type:bigint;not null;uniqueIndex:idx_coupon,priority:1;comment:ID" json:"coupon_id"` // ID
	Code           string    `gorm:"column:code;type:varchar(64);not null;index:idx_code,priority:1" json:"code"`
	CustomerID     int64     `gorm:"column:customer_id;type:bigint;not null;index:idx_customer,priority:1;comment:ID" json:"customer_id"` // ID
	UserID         int64     `gorm:"column:user_id;type:bigint;not null;index:idx_user,priority:1;comment:ID" json:"user_id"`             // ID
	SupplierID     int64     `gorm:"column:supplier_id;type:bigint;not null;index:idx_supplier,priority:1;comment:ID" json:"supplier_id"` // ID
	VerifyTime     time.Time `gorm:"column:verify_time;type:datetime;not null;index:idx_time,priority:1" json:"verify_time"`
	VerifyAmount   float64   `gorm:"column:verify_amount;type:decimal(10,2);not null" json:"verify_amount"`
	VerifyLocation string    `gorm:"column:verify_location;type:varchar(128)" json:"verify_location"`
	Operator       int64     `gorm:"column:operator;type:bigint;not null;comment:()" json:"operator"` // ()
	DeviceNo       string    `gorm:"column:device_no;type:varchar(64)" json:"device_no"`
	Remark         string    `gorm:"column:remark;type:varchar(255)" json:"remark"`
	CreateTime     time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName CouponVerify's table name
func (*CouponVerify) TableName() string {
	return TableNameCouponVerify
}
