// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sql_model

import (
	"time"
)

const TableNameCouponIssue = "coupon_issue"

// CouponIssue mapped from table <coupon_issue>
type CouponIssue struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CouponID     int64     `gorm:"column:coupon_id;type:bigint;not null;index:idx_coupon,priority:1;comment:ID" json:"coupon_id"`       // ID
	BatchID      int64     `gorm:"column:batch_id;type:bigint;not null;index:idx_batch,priority:1;comment:ID" json:"batch_id"`          // ID
	CustomerID   int64     `gorm:"column:customer_id;type:bigint;not null;index:idx_customer,priority:1;comment:ID" json:"customer_id"` // ID
	UserID       int64     `gorm:"column:user_id;type:bigint;not null;index:idx_user,priority:1;comment:ID" json:"user_id"`             // ID
	IssueChannel int32     `gorm:"column:issue_channel;type:tinyint;not null;comment::1H5 2APP 3 4API" json:"issue_channel"`            // :1H5 2APP 3 4API
	IssueTime    time.Time `gorm:"column:issue_time;type:datetime;not null" json:"issue_time"`
	Operator     int64     `gorm:"column:operator;type:bigint;comment:()" json:"operator"` // ()
	CreateTime   time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName CouponIssue's table name
func (*CouponIssue) TableName() string {
	return TableNameCouponIssue
}
