// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sql_model

import (
	"time"
)

const TableNameCoupon = "coupon"

// Coupon mapped from table <coupon>
type Coupon struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Code         string    `gorm:"column:code;type:varchar(64);not null;uniqueIndex:idx_code,priority:1" json:"code"`
	BatchID      int64     `gorm:"column:batch_id;type:bigint;not null;index:idx_batch,priority:1" json:"batch_id"`
	CustomerID   int64     `gorm:"column:customer_id;type:bigint;not null;index:idx_customer,priority:1;comment:ID" json:"customer_id"` // ID
	CouponType   int32     `gorm:"column:coupon_type;type:tinyint;not null" json:"coupon_type"`
	FaceValue    float64   `gorm:"column:face_value;type:decimal(10,2);not null" json:"face_value"`
	UserID       int64     `gorm:"column:user_id;type:bigint;index:idx_user,priority:1;comment:ID" json:"user_id"`                    // ID
	SupplierID   int64     `gorm:"column:supplier_id;type:bigint;comment:ID" json:"supplier_id"`                                      // ID
	Status       int32     `gorm:"column:status;type:tinyint;not null;index:idx_status,priority:1;comment:0: 1: 2: 3:" json:"status"` // 0: 1: 2: 3:
	GenerateTime time.Time `gorm:"column:generate_time;type:datetime;not null" json:"generate_time"`
	IssueTime    time.Time `gorm:"column:issue_time;type:datetime" json:"issue_time"`
	UseTime      time.Time `gorm:"column:use_time;type:datetime" json:"use_time"`
	ValidStart   time.Time `gorm:"column:valid_start;type:datetime;not null" json:"valid_start"`
	ValidEnd     time.Time `gorm:"column:valid_end;type:datetime;not null;index:idx_valid,priority:1" json:"valid_end"`
	CreateTime   time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime   time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Coupon's table name
func (*Coupon) TableName() string {
	return TableNameCoupon
}
