// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sql_model

import (
	"time"
)

const TableNameCouponBatch = "coupon_batch"

// CouponBatch mapped from table <coupon_batch>
type CouponBatch struct {
	ID             int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	BatchNo        string    `gorm:"column:batch_no;type:varchar(64);not null;uniqueIndex:idx_batch_no,priority:1" json:"batch_no"`
	CustomerID     int64     `gorm:"column:customer_id;type:bigint;not null;index:idx_customer,priority:1" json:"customer_id"`
	Name           string    `gorm:"column:name;type:varchar(128);not null" json:"name"`
	CouponType     int32     `gorm:"column:coupon_type;type:tinyint;not null;comment::1 2 3..." json:"coupon_type"` // :1 2 3...
	FaceValue      float64   `gorm:"column:face_value;type:decimal(10,2);not null" json:"face_value"`
	TotalCount     int32     `gorm:"column:total_count;type:int;not null" json:"total_count"`
	RemainingCount int32     `gorm:"column:remaining_count;type:int;not null" json:"remaining_count"`
	ValidStart     time.Time `gorm:"column:valid_start;type:datetime;not null;index:idx_valid_time,priority:1" json:"valid_start"`
	ValidEnd       time.Time `gorm:"column:valid_end;type:datetime;not null;index:idx_valid_time,priority:2" json:"valid_end"`
	Status         int32     `gorm:"column:status;type:tinyint;not null;comment:0: 1: 2: 3:" json:"status"` // 0: 1: 2: 3:
	CreateUser     int64     `gorm:"column:create_user;type:bigint;not null" json:"create_user"`
	CreateTime     time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName CouponBatch's table name
func (*CouponBatch) TableName() string {
	return TableNameCouponBatch
}
