// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sql_model

import (
	"time"
)

const TableNameCustomer = "customer"

// Customer mapped from table <customer>
type Customer struct {
	ID              int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name            string    `gorm:"column:name;type:varchar(128);not null" json:"name"`
	Code            string    `gorm:"column:code;type:varchar(64);not null;uniqueIndex:idx_code,priority:1" json:"code"`
	ContactName     string    `gorm:"column:contact_name;type:varchar(64);not null" json:"contact_name"`
	ContactPhone    string    `gorm:"column:contact_phone;type:varchar(20);not null" json:"contact_phone"`
	Address         string    `gorm:"column:address;type:varchar(255)" json:"address"`
	BusinessLicense string    `gorm:"column:business_license;type:varchar(128)" json:"business_license"`
	ContractStart   time.Time `gorm:"column:contract_start;type:date;not null" json:"contract_start"`
	ContractEnd     time.Time `gorm:"column:contract_end;type:date;not null" json:"contract_end"`
	SettlementCycle int32     `gorm:"column:settlement_cycle;type:tinyint;not null;comment::1 2 3" json:"settlement_cycle"` // :1 2 3
	SettlementRate  float64   `gorm:"column:settlement_rate;type:decimal(5,2);not null;comment:(%)" json:"settlement_rate"` // (%)
	Status          int32     `gorm:"column:status;type:tinyint;not null;default:1;comment:0: 1:" json:"status"`            // 0: 1:
	CreateTime      time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime      time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
