// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sql_model

import (
	"time"
)

const TableNameKmExpansionKeyword = "km_expansion_keyword"

// KmExpansionKeyword mapped from table <km_expansion_keyword>
type KmExpansionKeyword struct {
	ID              int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:关键词id,递增" json:"id"`                                                                                                            // 关键词id,递增
	Keyword         string    `gorm:"column:keyword;type:varchar(256);not null;uniqueIndex:uniq_task_keyword,priority:2;comment:关键词" json:"keyword"`                                                                                      // 关键词
	TaskID          int64     `gorm:"column:task_id;type:bigint unsigned;not null;uniqueIndex:uniq_task_keyword,priority:1;index:idx_task_level_expanded,priority:1;index:idx_task_parent_source,priority:1;comment:任务id" json:"task_id"` // 任务id
	BusinessID      int64     `gorm:"column:business_id;type:bigint unsigned;not null;comment:业务id" json:"business_id"`                                                                                                                   // 业务id
	RootKeyword     string    `gorm:"column:root_keyword;type:varchar(256);not null;comment:根词" json:"root_keyword"`                                                                                                                      // 根词
	ParentKeyword   string    `gorm:"column:parent_keyword;type:varchar(256);not null;index:idx_task_parent_source,priority:2;comment:父词" json:"parent_keyword"`                                                                          // 父词
	CrawlLevel      int32     `gorm:"column:crawl_level;type:int unsigned;not null;index:idx_task_level_expanded,priority:2;comment:当前所属抓取层级" json:"crawl_level"`                                                                         // 当前所属抓取层级
	KeywordSource   int32     `gorm:"column:keyword_source;type:int unsigned;not null;index:idx_task_parent_source,priority:3;comment:关键词来源，0-根词默认，1-来源candidate，2-来源related" json:"keyword_source"`                                      // 关键词来源，0-根词默认，1-来源candidate，2-来源related
	IsSubmitted     bool      `gorm:"column:is_submitted;type:tinyint(1);not null;comment:是否提交" json:"is_submitted"`                                                                                                                      // 是否提交
	IsCandidateDone bool      `gorm:"column:is_candidate_done;type:tinyint(1);not null;comment:候选词是否已就绪" json:"is_candidate_done"`                                                                                                        // 候选词是否已就绪
	IsRelatedDone   bool      `gorm:"column:is_related_done;type:tinyint(1);not null;comment:关联词是否已就绪" json:"is_related_done"`                                                                                                            // 关联词是否已就绪
	IsExpanded      bool      `gorm:"column:is_expanded;type:tinyint(1);not null;index:idx_task_level_expanded,priority:3;comment:是否处理完毕" json:"is_expanded"`                                                                             // 是否处理完毕
	CreatedAt       time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                                                                                          // 创建时间
	UpdatedAt       time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                                                                          // 更新时间
}

// TableName KmExpansionKeyword's table name
func (*KmExpansionKeyword) TableName() string {
	return TableNameKmExpansionKeyword
}
