// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sql_model

import (
	"time"
)

const TableNameSettlement = "settlement"

// Settlement mapped from table <settlement>
type Settlement struct {
	ID             int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SettlementNo   string    `gorm:"column:settlement_no;type:varchar(64);not null;uniqueIndex:idx_settlement_no,priority:1" json:"settlement_no"`
	CustomerID     int64     `gorm:"column:customer_id;type:bigint;not null;index:idx_customer,priority:1;comment:ID" json:"customer_id"` // ID
	SupplierID     int64     `gorm:"column:supplier_id;type:bigint;not null;index:idx_supplier,priority:1;comment:ID" json:"supplier_id"` // ID
	StartDate      time.Time `gorm:"column:start_date;type:date;not null" json:"start_date"`
	EndDate        time.Time `gorm:"column:end_date;type:date;not null;index:idx_date,priority:1" json:"end_date"`
	TotalAmount    float64   `gorm:"column:total_amount;type:decimal(12,2);not null" json:"total_amount"`
	PlatformFee    float64   `gorm:"column:platform_fee;type:decimal(12,2);not null" json:"platform_fee"`
	SupplierAmount float64   `gorm:"column:supplier_amount;type:decimal(12,2);not null" json:"supplier_amount"`
	VerifyCount    int32     `gorm:"column:verify_count;type:int;not null" json:"verify_count"`
	Status         int32     `gorm:"column:status;type:tinyint;not null;index:idx_status,priority:1;comment:0: 1: 2: 3:" json:"status"` // 0: 1: 2: 3:
	PaymentTime    time.Time `gorm:"column:payment_time;type:datetime" json:"payment_time"`
	PaymentProof   string    `gorm:"column:payment_proof;type:varchar(255)" json:"payment_proof"`
	Remark         string    `gorm:"column:remark;type:varchar(255)" json:"remark"`
	CreateUser     int64     `gorm:"column:create_user;type:bigint;not null" json:"create_user"`
	CreateTime     time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Settlement's table name
func (*Settlement) TableName() string {
	return TableNameSettlement
}
