// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sql_model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameTTestTable = "t_test_table"

// TTestTable mapped from table <t_test_table>
type TTestTable struct {
	ID                   int32                 `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name                 string                `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Age                  int32                 `gorm:"column:age;type:tinyint" json:"age"`
	Salary               float64               `gorm:"column:salary;type:decimal(10,2)" json:"salary"`
	IsActive             bool                  `gorm:"column:is_active;type:tinyint(1);default:1" json:"is_active"`
	BirthDate            time.Time             `gorm:"column:birth_date;type:date" json:"birth_date"`
	StartTime            time.Time             `gorm:"column:start_time;type:time" json:"start_time"`
	RegistrationDatetime time.Time             `gorm:"column:registration_datetime;type:datetime" json:"registration_datetime"`
	Details              string                `gorm:"column:details;type:text" json:"details"`
	Status               string                `gorm:"column:status;type:enum('active','inactive','pending');default:active" json:"status"`
	CreatedAt            time.Time             `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	DeletedAt            soft_delete.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
}

// TableName TTestTable's table name
func (*TTestTable) TableName() string {
	return TableNameTTestTable
}
