// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"singo/dal/sql_model"
)

func newCouponVerify(db *gorm.DB, opts ...gen.DOOption) couponVerify {
	_couponVerify := couponVerify{}

	_couponVerify.couponVerifyDo.UseDB(db, opts...)
	_couponVerify.couponVerifyDo.UseModel(&sql_model.CouponVerify{})

	tableName := _couponVerify.couponVerifyDo.TableName()
	_couponVerify.ALL = field.NewAsterisk(tableName)
	_couponVerify.ID = field.NewInt64(tableName, "id")
	_couponVerify.CouponID = field.NewInt64(tableName, "coupon_id")
	_couponVerify.Code = field.NewString(tableName, "code")
	_couponVerify.CustomerID = field.NewInt64(tableName, "customer_id")
	_couponVerify.UserID = field.NewInt64(tableName, "user_id")
	_couponVerify.SupplierID = field.NewInt64(tableName, "supplier_id")
	_couponVerify.VerifyTime = field.NewTime(tableName, "verify_time")
	_couponVerify.VerifyAmount = field.NewFloat64(tableName, "verify_amount")
	_couponVerify.VerifyLocation = field.NewString(tableName, "verify_location")
	_couponVerify.Operator = field.NewInt64(tableName, "operator")
	_couponVerify.DeviceNo = field.NewString(tableName, "device_no")
	_couponVerify.Remark = field.NewString(tableName, "remark")
	_couponVerify.CreateTime = field.NewTime(tableName, "create_time")

	_couponVerify.fillFieldMap()

	return _couponVerify
}

type couponVerify struct {
	couponVerifyDo couponVerifyDo

	ALL            field.Asterisk
	ID             field.Int64
	CouponID       field.Int64 // ID
	Code           field.String
	CustomerID     field.Int64 // ID
	UserID         field.Int64 // ID
	SupplierID     field.Int64 // ID
	VerifyTime     field.Time
	VerifyAmount   field.Float64
	VerifyLocation field.String
	Operator       field.Int64 // ()
	DeviceNo       field.String
	Remark         field.String
	CreateTime     field.Time

	fieldMap map[string]field.Expr
}

func (c couponVerify) Table(newTableName string) *couponVerify {
	c.couponVerifyDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c couponVerify) As(alias string) *couponVerify {
	c.couponVerifyDo.DO = *(c.couponVerifyDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *couponVerify) updateTableName(table string) *couponVerify {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.CouponID = field.NewInt64(table, "coupon_id")
	c.Code = field.NewString(table, "code")
	c.CustomerID = field.NewInt64(table, "customer_id")
	c.UserID = field.NewInt64(table, "user_id")
	c.SupplierID = field.NewInt64(table, "supplier_id")
	c.VerifyTime = field.NewTime(table, "verify_time")
	c.VerifyAmount = field.NewFloat64(table, "verify_amount")
	c.VerifyLocation = field.NewString(table, "verify_location")
	c.Operator = field.NewInt64(table, "operator")
	c.DeviceNo = field.NewString(table, "device_no")
	c.Remark = field.NewString(table, "remark")
	c.CreateTime = field.NewTime(table, "create_time")

	c.fillFieldMap()

	return c
}

func (c *couponVerify) WithContext(ctx context.Context) *couponVerifyDo {
	return c.couponVerifyDo.WithContext(ctx)
}

func (c couponVerify) TableName() string { return c.couponVerifyDo.TableName() }

func (c couponVerify) Alias() string { return c.couponVerifyDo.Alias() }

func (c couponVerify) Columns(cols ...field.Expr) gen.Columns {
	return c.couponVerifyDo.Columns(cols...)
}

func (c *couponVerify) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *couponVerify) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 13)
	c.fieldMap["id"] = c.ID
	c.fieldMap["coupon_id"] = c.CouponID
	c.fieldMap["code"] = c.Code
	c.fieldMap["customer_id"] = c.CustomerID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["supplier_id"] = c.SupplierID
	c.fieldMap["verify_time"] = c.VerifyTime
	c.fieldMap["verify_amount"] = c.VerifyAmount
	c.fieldMap["verify_location"] = c.VerifyLocation
	c.fieldMap["operator"] = c.Operator
	c.fieldMap["device_no"] = c.DeviceNo
	c.fieldMap["remark"] = c.Remark
	c.fieldMap["create_time"] = c.CreateTime
}

func (c couponVerify) clone(db *gorm.DB) couponVerify {
	c.couponVerifyDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c couponVerify) replaceDB(db *gorm.DB) couponVerify {
	c.couponVerifyDo.ReplaceDB(db)
	return c
}

type couponVerifyDo struct{ gen.DO }

func (c couponVerifyDo) Debug() *couponVerifyDo {
	return c.withDO(c.DO.Debug())
}

func (c couponVerifyDo) WithContext(ctx context.Context) *couponVerifyDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c couponVerifyDo) ReadDB() *couponVerifyDo {
	return c.Clauses(dbresolver.Read)
}

func (c couponVerifyDo) WriteDB() *couponVerifyDo {
	return c.Clauses(dbresolver.Write)
}

func (c couponVerifyDo) Session(config *gorm.Session) *couponVerifyDo {
	return c.withDO(c.DO.Session(config))
}

func (c couponVerifyDo) Clauses(conds ...clause.Expression) *couponVerifyDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c couponVerifyDo) Returning(value interface{}, columns ...string) *couponVerifyDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c couponVerifyDo) Not(conds ...gen.Condition) *couponVerifyDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c couponVerifyDo) Or(conds ...gen.Condition) *couponVerifyDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c couponVerifyDo) Select(conds ...field.Expr) *couponVerifyDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c couponVerifyDo) Where(conds ...gen.Condition) *couponVerifyDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c couponVerifyDo) Order(conds ...field.Expr) *couponVerifyDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c couponVerifyDo) Distinct(cols ...field.Expr) *couponVerifyDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c couponVerifyDo) Omit(cols ...field.Expr) *couponVerifyDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c couponVerifyDo) Join(table schema.Tabler, on ...field.Expr) *couponVerifyDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c couponVerifyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *couponVerifyDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c couponVerifyDo) RightJoin(table schema.Tabler, on ...field.Expr) *couponVerifyDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c couponVerifyDo) Group(cols ...field.Expr) *couponVerifyDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c couponVerifyDo) Having(conds ...gen.Condition) *couponVerifyDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c couponVerifyDo) Limit(limit int) *couponVerifyDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c couponVerifyDo) Offset(offset int) *couponVerifyDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c couponVerifyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *couponVerifyDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c couponVerifyDo) Unscoped() *couponVerifyDo {
	return c.withDO(c.DO.Unscoped())
}

func (c couponVerifyDo) Create(values ...*sql_model.CouponVerify) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c couponVerifyDo) CreateInBatches(values []*sql_model.CouponVerify, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c couponVerifyDo) Save(values ...*sql_model.CouponVerify) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c couponVerifyDo) First() (*sql_model.CouponVerify, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*sql_model.CouponVerify), nil
	}
}

func (c couponVerifyDo) Take() (*sql_model.CouponVerify, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*sql_model.CouponVerify), nil
	}
}

func (c couponVerifyDo) Last() (*sql_model.CouponVerify, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*sql_model.CouponVerify), nil
	}
}

func (c couponVerifyDo) Find() ([]*sql_model.CouponVerify, error) {
	result, err := c.DO.Find()
	return result.([]*sql_model.CouponVerify), err
}

func (c couponVerifyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*sql_model.CouponVerify, err error) {
	buf := make([]*sql_model.CouponVerify, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c couponVerifyDo) FindInBatches(result *[]*sql_model.CouponVerify, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c couponVerifyDo) Attrs(attrs ...field.AssignExpr) *couponVerifyDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c couponVerifyDo) Assign(attrs ...field.AssignExpr) *couponVerifyDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c couponVerifyDo) Joins(fields ...field.RelationField) *couponVerifyDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c couponVerifyDo) Preload(fields ...field.RelationField) *couponVerifyDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c couponVerifyDo) FirstOrInit() (*sql_model.CouponVerify, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*sql_model.CouponVerify), nil
	}
}

func (c couponVerifyDo) FirstOrCreate() (*sql_model.CouponVerify, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*sql_model.CouponVerify), nil
	}
}

func (c couponVerifyDo) FindByPage(offset int, limit int) (result []*sql_model.CouponVerify, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c couponVerifyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c couponVerifyDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c couponVerifyDo) Delete(models ...*sql_model.CouponVerify) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *couponVerifyDo) withDO(do gen.Dao) *couponVerifyDo {
	c.DO = *do.(*gen.DO)
	return c
}
